name: 'PGATS - Continuous Integration - Level 1'
on:
  workflow_dispatch: 
jobs:

  tests:
    runs-on: ['ubuntu-latest']

    steps: 

      - uses: actions/checkout@v4

      - name: Dependencies install
        run: npm ci

      - name: Running e2e tests
        run: npm run test
      
      - uses: actions/upload-artifact@v4
        if: ${{ !success() && !cancelled() }}
        with: 
          name: Test report
          path: ./cypress/reports